name:                codechef2021
version:             0.1.0.0
github:              "githubuser/codechef2021"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/codechef2021#readme>

dependencies:
- base >= 4.7 && < 5
- array

executables:
  divthree:
    main:                Main.hs
    source-dirs:         divthree
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  decodeit:
    main:                Main.hs
    source-dirs:         decodeit
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  fairelct:
    main:                Main.hs
    source-dirs:         fairelct
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  billrd:
    main:                Main.hs
    source-dirs:         billrd
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  codechef2021-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - codechef2021
